# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"f\n\x0fOptimizeRequest\x12\x0e\n\x06ItemID\x18\x01 \x01(\t\x12\x14\n\x0c\x43urrentStock\x18\x02 \x01(\x05\x12\x17\n\x0fPredictedDemand\x18\x03 \x01(\x05\x12\x14\n\x0cReorderLevel\x18\x04 \x01(\x05\"K\n\rDemandRequest\x12\x0e\n\x06ItemID\x18\x01 \x01(\t\x12\x14\n\x0c\x43urrentStock\x18\x02 \x01(\x05\x12\x14\n\x0cReorderLevel\x18\x03 \x01(\x05\"_\n\x10OptimizeResponse\x12\x17\n\x0fReorderQuantity\x18\x01 \x01(\x05\x12\x32\n\nadjustment\x18\x02 \x01(\x0e\x32\x1e.inventory.Inventoryadjustment\")\n\x0e\x44\x65mandResponse\x12\x17\n\x0f\x44\x65mandPredicted\x18\x01 \x01(\x05*3\n\x13Inventoryadjustment\x12\x0c\n\x08SCALE_UP\x10\x00\x12\x0e\n\nSCALE_DOWN\x10\x01\x32\x9f\x01\n\x15InventoryOptimization\x12\x45\n\x08Optimize\x12\x1a.inventory.OptimizeRequest\x1a\x1b.inventory.OptimizeResponse\"\x00\x12?\n\x06\x44\x65mand\x12\x18.inventory.DemandRequest\x1a\x19.inventory.DemandResponse\"\x00\x42\x14\n\x10\x63om.proto.demandP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.proto.demandP\001'
  _globals['_INVENTORYADJUSTMENT']._serialized_start=351
  _globals['_INVENTORYADJUSTMENT']._serialized_end=402
  _globals['_OPTIMIZEREQUEST']._serialized_start=30
  _globals['_OPTIMIZEREQUEST']._serialized_end=132
  _globals['_DEMANDREQUEST']._serialized_start=134
  _globals['_DEMANDREQUEST']._serialized_end=209
  _globals['_OPTIMIZERESPONSE']._serialized_start=211
  _globals['_OPTIMIZERESPONSE']._serialized_end=306
  _globals['_DEMANDRESPONSE']._serialized_start=308
  _globals['_DEMANDRESPONSE']._serialized_end=349
  _globals['_INVENTORYOPTIMIZATION']._serialized_start=405
  _globals['_INVENTORYOPTIMIZATION']._serialized_end=564
# @@protoc_insertion_point(module_scope)
