# api/Dockerfile
FROM python:3.8

COPY requirements.txt .
COPY inventory_pb2.py .
COPY inventory_pb2_grpc.py .
COPY ./api .



RUN pip install -r requirements.txt requests

EXPOSE 8000

CMD ["python","app.py"]
